### ISSUE TITLE
Poor performance with many chests

### ISSUE THREAD

**Issue by NiftyManiac** [justarandomgeek/factorio-bad-chest#3] opened 2017-02-12 04:14 UTC
If I put down around twenty chests, wired but with no signals being passed, I get serious UPS loss; recursive-blueprints starts taking up to 20-30ms per tick on it's own.

I can see that every tick, every chest looks at it's incoming signals. I added in a fail-early check to the top of onTickDeployer to check just the construct/deconstruct command signals, and that brought down the update time to 5ms for this mod.

That's still pretty bad though. Is there any way to improve this performance? First thing that comes to mind is having some kind of invisible entity with a circuit condition, and checking that condition instead of using get_signal. That'd be a hassle. The chests will usually not be doing anything, so I'm sure there's a way to optimize this.

**Comment by justarandomgeek** [comment] 2017-02-12 15:52
The performance of this is pretty much unavoidably shit. In order to handle signal pulses correctly (and all these messages will be) you have to check for them *every single tick*, which is a lot of script. In any case, I've mostly abandoned this mod at this point in favor of [ConMan](https://github.com/justarandomgeek/factorio-conman) which I hope to post a release of later today - it's a simpler control set but will suffer from the same check-every-tick problem.

**Comment by NiftyManiac** [comment] 2017-02-12 16:41
Oooh, ConMan looks cool; looking forward. Especially the wire connection commands. I've got a big project based on this mod going on, though :).

I haven't thought about this a ton, but there's definitely ways to deal with this... just maybe very very ugly ones. The good thing is that due to how robots work, blueprints aren't really time-sensitive. So you could do something like make an invisible shift-register of combinators under each chest, and every X ticks clear out the register and execute all of the stored commands. Pain in the ass, though; I wish there was a way to buffer signals internally without on_tick. Factorio modding is frustrating sometimes...

**Comment by justarandomgeek** [comment] 2017-02-12 17:21
Which commands are you actively using currently? Are you providing any non-command signals on the same wire (while idle or in use)?

Can you post your save file?

**Comment by NiftyManiac** [comment] 2017-02-12 17:43
Well the performance issues are when it's idling with no commands. Since planning complex deconstruction commands is a pain with just rectangles, I have a bunch of empty deployers sitting around wired together so they simultaneously deconstruct rectangles with slightly different parameters and origins. There are non-command signals on the wire, which is why adding the fail-early check for just construction robots and deconstruction planners helped.

I can post the save later if you really want but it's pretty reproducible.

**Comment by justarandomgeek** [comment] 2017-02-12 17:51
non-empty idle circuits is almost certainly the cause here - that's not a thing I would have tested. I'll go through this and see what I can optimize when I get a chance. (Or you're welcome to PR the changes you've made, or simply fork the project and take over (like I did in the first place!), of course! :) )

**Comment by justarandomgeek** [comment] 2017-02-26 17:24
#4 merged to master, which should help a lot with this :)

I'll bump the version number and post a new release later today...

**Comment by NiftyManiac** [comment] 2017-03-04 03:34
*cough cough*

**Closed as completed** 2017-04-11 00:24 UTC
